### ISSUE TITLE
Show total staked value of the Farm and individual share

### ISSUE THREAD

**Issue by jeisses** [effectai/bridge-frontend#11]
## Description
The Farm data should show the total USD value of the staked LP tokens in the pool. It should also show the USD value of an individuals share if logged in.

## Notes
Some notes on how to calculate this from Discord:

This is the LP contract. You can look at the total tokens for WBNB and EFX
Take your total LP tokens, and divide them by the total of number of LP tokens that exist. 
This fraction then can be multipled by the current WBNB and EFX in the contract, that share is your portion of the liquidity and all you need to do from there is multiple both by the current price of BNB and EFX respectively to get their current values.

**Comment by MiggySmallz** [comment]
![Image](https://user-images.githubusercontent.com/22913608/196851398-5bc286fe-4b5d-4fc1-90e2-5d1a400987cc.png)

What to you think? The layout I think need to be refined and I am open to suggestions, but the USD values and connections in the backend should be correct and good to go.

**Comment by jeisses** [comment]
Great work! We just discussed some minor changes that need to happen for dispaly
