### ISSUE TITLE
Verify that the EOS->BSC bridge works again and enable it

### ISSUE THREAD

**Issue by jeisses** [effectai/bridge-frontend#33]
@djmbritt pTokens mentioned that the bridge works again. Could you verify their message, and if does enable it again?

**Comment by jeisses** [comment]
Also, the 1800 minimum swap is not being enforced. (it just hints the minimum as placeholder, but the UI doesn't stop us from submitting lower numbers)

**Comment by djmbritt** [comment]
I was able to confirm that the swaps are working as intended.
The receipts were not appearing in my wallet, so I was confused for a bit.

With this latest push, I've also addressed the points you've made above.
The new fee structure is weird, so I've added input fields that show how much the user will receive and how much they will pay in fees.

I've referenced [ptokens](https://dapp.ptokens.io/#/swap?asset=efx&from=eos&to=bsc) to make sure the amounts are correct.

**Comment by jeisses** [comment]
That is great, thanks :+1:
